from datetime import datetime
from pathlib import Path

today = datetime.now().strftime("%Y-%m-%d")
filename = f"_posts/{today}-autogen.md"

content = f"""---
layout: post
title: "Auto-generated Post"
date: {today}
---

This post was generated by Python at deploy time.
"""

Path("_posts").mkdir(exist_ok=True)
with open(filename, "w") as f:
    f.write(content)

print(f"Generated: {filename}")
